// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: base_go.proto

package usercmd

import (
	//"github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//http request data
type ReqHttpArgData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args []*ReqHttpArgData_KeyVal //`protobuf:"bytes,1,rep,name=Args,proto3" json:"Args,omitempty"` //
	Cmd  uint32                   //`protobuf:"varint,2,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
}

func (x *ReqHttpArgData) Reset() {
	*x = ReqHttpArgData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_go_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqHttpArgData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqHttpArgData) ProtoMessage() {}


func (x *ReqHttpArgData) ProtoReflect() protoreflect.Message {
	mi := &file_base_go_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

//////

func (m *ReqHttpArgData_KeyVal) Size() (n int){
	var l int
	_ = l
	l = len(m.Key)
	if l >0{
		n += 1 + l + encodeVarintSize(uint64(l))
	}
	l = len(m.Val)
	if l > 0 {
		n += 1+l +encodeVarintSize(uint64(l))
	}
	return n

}

//func (m *ReqHttpArgData) Marshal()([]byte, error){
//	data := make([]byte, m.Size())
//	_, err = m.MarrshalTo(data)
//	return data, err
//}

func (m *ReqHttpArgData) MarshalTo(dAtA []byte) (int, error){
	var i int
	var l int
	_ = l
	if len(m.Args) >0{
		for _, msg := range m.Args{
			dAtA[i] = 0xa
			i++
			encodeVarint(dAtA, &i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil{
				return 0, err
			}
			i+=n
		}
	}
	if m.Cmd != 0{
		dAtA[i] = 0x10
		i++
		encodeVarint(dAtA, &i, uint64(m.Cmd))
	}

	return i, nil
}

func (m *ReqHttpArgData_KeyVal) MarshalTo(dAtA []byte) (int, error){
	var i int
	var l int
	_ = l
	if len(m.Key) > 0{
		dAtA[i] = 0xa
		i++
		encodeVarint(dAtA, &i, uint64(len(m.Key)))
		i+= copy(dAtA[i:],m.Key)
	}
	if len(m.Val) > 0 {
		dAtA[i] = 0x12
		i++
		encodeVarint(dAtA, &i, uint64(len(m.Val)))
		i += copy(dAtA[i:], m.Val)
	}
	return i, nil
}


// Deprecated: Use ReqHttpArgData.ProtoReflect.Descriptor instead.
func (*ReqHttpArgData) Descriptor() ([]byte, []int) {
	return file_base_go_proto_rawDescGZIP(), []int{0}
}

func (x *ReqHttpArgData) GetArgs() []*ReqHttpArgData_KeyVal {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ReqHttpArgData) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

type ReqHttpArgData_KeyVal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string //`protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Val string //`protobuf:"bytes,2,opt,name=Val,proto3" json:"Val,omitempty"`
}

func (x *ReqHttpArgData_KeyVal) Reset() {
	*x = ReqHttpArgData_KeyVal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_go_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqHttpArgData_KeyVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqHttpArgData_KeyVal) ProtoMessage() {}

func (x *ReqHttpArgData_KeyVal) ProtoReflect() protoreflect.Message {
	mi := &file_base_go_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqHttpArgData_KeyVal.ProtoReflect.Descriptor instead.
func (*ReqHttpArgData_KeyVal) Descriptor() ([]byte, []int) {
	return file_base_go_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ReqHttpArgData_KeyVal) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReqHttpArgData_KeyVal) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

var File_base_go_proto protoreflect.FileDescriptor

var file_base_go_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6d, 0x64, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x71,
	0x48, 0x74, 0x74, 0x70, 0x41, 0x72, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x04, 0x41,
	0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x63, 0x6d, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x74, 0x74, 0x70, 0x41, 0x72, 0x67, 0x44, 0x61,
	0x74, 0x61, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x52, 0x04, 0x41, 0x72, 0x67, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x43, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x43, 0x6d,
	0x64, 0x1a, 0x2c, 0x0a, 0x06, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x56, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x56, 0x61, 0x6c, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6d, 0x64, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_base_go_proto_rawDescOnce sync.Once
	file_base_go_proto_rawDescData = file_base_go_proto_rawDesc
)

func file_base_go_proto_rawDescGZIP() []byte {
	file_base_go_proto_rawDescOnce.Do(func() {
		file_base_go_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_go_proto_rawDescData)
	})
	return file_base_go_proto_rawDescData
}

var file_base_go_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_base_go_proto_goTypes = []interface{}{
	(*ReqHttpArgData)(nil),        // 0: usercmd.ReqHttpArgData
	(*ReqHttpArgData_KeyVal)(nil), // 1: usercmd.ReqHttpArgData.KeyVal
}
var file_base_go_proto_depIdxs = []int32{
	1, // 0: usercmd.ReqHttpArgData.Args:type_name -> usercmd.ReqHttpArgData.KeyVal
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_base_go_proto_init() }
func file_base_go_proto_init() {
	if File_base_go_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_base_go_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqHttpArgData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_go_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqHttpArgData_KeyVal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_go_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_go_proto_goTypes,
		DependencyIndexes: file_base_go_proto_depIdxs,
		MessageInfos:      file_base_go_proto_msgTypes,
	}.Build()
	File_base_go_proto = out.File
	file_base_go_proto_rawDesc = nil
	file_base_go_proto_goTypes = nil
	file_base_go_proto_depIdxs = nil
}
