// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: player.proto

package usercmd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_Login        MsgType = 1
	MsgType_ReqIntoFRoom MsgType = 5
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		1: "Login",
		5: "ReqIntoFRoom",
	}
	MsgType_value = map[string]int32{
		"Login":        1,
		"ReqIntoFRoom": 5,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_player_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_player_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MsgType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MsgType(num)
	return nil
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

type ReqIntoRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId      *uint64 `protobuf:"varint,1,req,name=UId" json:"UId,omitempty"`
	UserName *string `protobuf:"bytes,2,opt,name=UserName" json:"UserName,omitempty"`
}

func (x *ReqIntoRoom) Reset() {
	*x = ReqIntoRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqIntoRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqIntoRoom) ProtoMessage() {}

func (x *ReqIntoRoom) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqIntoRoom.ProtoReflect.Descriptor instead.
func (*ReqIntoRoom) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

func (x *ReqIntoRoom) GetUId() uint64 {
	if x != nil && x.UId != nil {
		return *x.UId
	}
	return 0
}

func (x *ReqIntoRoom) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

//Request Into room
type RetIntoFRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err     *uint32 `protobuf:"varint,1,req,name=Err" json:"Err,omitempty"`
	Addr    *string `protobuf:"bytes,2,opt,name=Addr" json:"Addr,omitempty"`
	Key     *string `protobuf:"bytes,3,opt,name=Key" json:"Key,omitempty"`
	UId     *uint64 `protobuf:"varint,4,opt,name=UId" json:"UId,omitempty"`
	Tips    *uint32 `protobuf:"varint,5,opt,name=Tips" json:"Tips,omitempty"`
	RoomId  *uint32 `protobuf:"varint,6,opt,name=RoomId" json:"RoomId,omitempty"`
	Priv    *uint32 `protobuf:"varint,7,opt,name=Priv" json:"Priv,omitempty"`
	OtherId *uint64 `protobuf:"varint,8,opt,name=OtherId" json:"OtherId,omitempty"`
	AddrAll *string `protobuf:"bytes,9,opt,name=AddrAll" json:"AddrAll,omitempty"`
	PowerId *uint64 `protobuf:"varint,10,opt,name=PowerId" json:"PowerId,omitempty"`
	NewSync *bool   `protobuf:"varint,11,opt,name=NewSync" json:"NewSync,omitempty"`
}

func (x *RetIntoFRoom) Reset() {
	*x = RetIntoFRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetIntoFRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetIntoFRoom) ProtoMessage() {}

func (x *RetIntoFRoom) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetIntoFRoom.ProtoReflect.Descriptor instead.
func (*RetIntoFRoom) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{1}
}

func (x *RetIntoFRoom) GetErr() uint32 {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return 0
}

func (x *RetIntoFRoom) GetAddr() string {
	if x != nil && x.Addr != nil {
		return *x.Addr
	}
	return ""
}

func (x *RetIntoFRoom) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *RetIntoFRoom) GetUId() uint64 {
	if x != nil && x.UId != nil {
		return *x.UId
	}
	return 0
}

func (x *RetIntoFRoom) GetTips() uint32 {
	if x != nil && x.Tips != nil {
		return *x.Tips
	}
	return 0
}

func (x *RetIntoFRoom) GetRoomId() uint32 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

func (x *RetIntoFRoom) GetPriv() uint32 {
	if x != nil && x.Priv != nil {
		return *x.Priv
	}
	return 0
}

func (x *RetIntoFRoom) GetOtherId() uint64 {
	if x != nil && x.OtherId != nil {
		return *x.OtherId
	}
	return 0
}

func (x *RetIntoFRoom) GetAddrAll() string {
	if x != nil && x.AddrAll != nil {
		return *x.AddrAll
	}
	return ""
}

func (x *RetIntoFRoom) GetPowerId() uint64 {
	if x != nil && x.PowerId != nil {
		return *x.PowerId
	}
	return 0
}

func (x *RetIntoFRoom) GetNewSync() bool {
	if x != nil && x.NewSync != nil {
		return *x.NewSync
	}
	return false
}

var File_player_proto protoreflect.FileDescriptor

var file_player_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x63, 0x6d, 0x64, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x49, 0x6e, 0x74, 0x6f, 0x52, 0x6f,
	0x6f, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52,
	0x03, 0x55, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x80, 0x02, 0x0a, 0x0c, 0x52, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x6f, 0x46, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x03,
	0x45, 0x72, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x69, 0x70, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x69, 0x70, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x72, 0x69, 0x76, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x50, 0x72, 0x69, 0x76, 0x12, 0x18, 0x0a, 0x07, 0x4f,
	0x74, 0x68, 0x65, 0x72, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x4f, 0x74,
	0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x41, 0x6c, 0x6c,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x41, 0x6c, 0x6c, 0x12,
	0x18, 0x0a, 0x07, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x77,
	0x53, 0x79, 0x6e, 0x63, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x4e, 0x65, 0x77, 0x53,
	0x79, 0x6e, 0x63, 0x2a, 0x26, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09,
	0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x65, 0x71,
	0x49, 0x6e, 0x74, 0x6f, 0x46, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x05, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x2f, 0x3b, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6d, 0x64,
}

var (
	file_player_proto_rawDescOnce sync.Once
	file_player_proto_rawDescData = file_player_proto_rawDesc
)

func file_player_proto_rawDescGZIP() []byte {
	file_player_proto_rawDescOnce.Do(func() {
		file_player_proto_rawDescData = protoimpl.X.CompressGZIP(file_player_proto_rawDescData)
	})
	return file_player_proto_rawDescData
}

var file_player_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_player_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_player_proto_goTypes = []interface{}{
	(MsgType)(0),         // 0: usercmd.MsgType
	(*ReqIntoRoom)(nil),  // 1: usercmd.ReqIntoRoom
	(*RetIntoFRoom)(nil), // 2: usercmd.RetIntoFRoom
}
var file_player_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_player_proto_init() }
func file_player_proto_init() {
	if File_player_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_player_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqIntoRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetIntoFRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_player_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_proto_goTypes,
		DependencyIndexes: file_player_proto_depIdxs,
		EnumInfos:         file_player_proto_enumTypes,
		MessageInfos:      file_player_proto_msgTypes,
	}.Build()
	File_player_proto = out.File
	file_player_proto_rawDesc = nil
	file_player_proto_goTypes = nil
	file_player_proto_depIdxs = nil
}
