// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: server.proto

package usercmd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdType int32

const (
	CmdType_None                CmdType = 0 // Placeholder
	CmdType_Login2              CmdType = 1 //++++++++++++++++++++++++
	CmdType_TSerUserNum         CmdType = 2
	CmdType_ChkReLogin          CmdType = 3
	CmdType_SyncRoomTeam        CmdType = 5
	CmdType_S2S                 CmdType = 6
	CmdType_InviteList          CmdType = 8
	CmdType_AddRoom             CmdType = 17
	CmdType_RemoveRoom          CmdType = 18
	CmdType_UpdateRoom          CmdType = 19
	CmdType_EndGame             CmdType = 20
	CmdType_UpdateServer        CmdType = 21 // Update player number
	CmdType_LoadCinfig          CmdType = 22
	CmdType_TJointRoom          CmdType = 32
	CmdType_HeartBeat           CmdType = 37 //------------------------------
	CmdType_SubscribeSetRoom    CmdType = 301
	CmdType_SubscribeStartRoom  CmdType = 304
	CmdType_SubscribeCancelRoom CmdType = 305
	CmdType_ServiceRegister     CmdType = 10001
	CmdType_ServiceHeartBeat    CmdType = 10002
)

// Enum value maps for CmdType.
var (
	CmdType_name = map[int32]string{
		0:     "None",
		1:     "Login2",
		2:     "TSerUserNum",
		3:     "ChkReLogin",
		5:     "SyncRoomTeam",
		6:     "S2S",
		8:     "InviteList",
		17:    "AddRoom",
		18:    "RemoveRoom",
		19:    "UpdateRoom",
		20:    "EndGame",
		21:    "UpdateServer",
		22:    "LoadCinfig",
		32:    "TJointRoom",
		37:    "HeartBeat",
		301:   "SubscribeSetRoom",
		304:   "SubscribeStartRoom",
		305:   "SubscribeCancelRoom",
		10001: "ServiceRegister",
		10002: "ServiceHeartBeat",
	}
	CmdType_value = map[string]int32{
		"None":                0,
		"Login2":              1,
		"TSerUserNum":         2,
		"ChkReLogin":          3,
		"SyncRoomTeam":        5,
		"S2S":                 6,
		"InviteList":          8,
		"AddRoom":             17,
		"RemoveRoom":          18,
		"UpdateRoom":          19,
		"EndGame":             20,
		"UpdateServer":        21,
		"LoadCinfig":          22,
		"TJointRoom":          32,
		"HeartBeat":           37,
		"SubscribeSetRoom":    301,
		"SubscribeStartRoom":  304,
		"SubscribeCancelRoom": 305,
		"ServiceRegister":     10001,
		"ServiceHeartBeat":    10002,
	}
)

func (x CmdType) Enum() *CmdType {
	p := new(CmdType)
	*p = x
	return p
}

func (x CmdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[0].Descriptor()
}

func (CmdType) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[0]
}

func (x CmdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdType.Descriptor instead.
func (CmdType) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

type ReqServiceHeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqServiceHeartBeat) Reset() {
	*x = ReqServiceHeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqServiceHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqServiceHeartBeat) ProtoMessage() {}

func (x *ReqServiceHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqServiceHeartBeat.ProtoReflect.Descriptor instead.
func (*ReqServiceHeartBeat) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

type RetServiceHeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetServiceHeartBeat) Reset() {
	*x = RetServiceHeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetServiceHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetServiceHeartBeat) ProtoMessage() {}

func (x *RetServiceHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetServiceHeartBeat.ProtoReflect.Descriptor instead.
func (*RetServiceHeartBeat) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

type ReqRegisterService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service string `protobuf:"bytes,1,opt,name=Service,proto3" json:"Service,omitempty"`
	Info    string `protobuf:"bytes,2,opt,name=Info,proto3" json:"Info,omitempty"`
}

func (x *ReqRegisterService) Reset() {
	*x = ReqRegisterService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqRegisterService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRegisterService) ProtoMessage() {}

func (x *ReqRegisterService) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRegisterService.ProtoReflect.Descriptor instead.
func (*ReqRegisterService) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *ReqRegisterService) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ReqRegisterService) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type RetRegisterService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetRegisterService) Reset() {
	*x = RetRegisterService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetRegisterService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetRegisterService) ProtoMessage() {}

func (x *RetRegisterService) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetRegisterService.ProtoReflect.Descriptor instead.
func (*RetRegisterService) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

//Verify between Server
type ReqServerLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"` // external net
	Key      string `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	SerType  uint32 `protobuf:"varint,3,opt,name=SerType,proto3" json:"SerType,omitempty"` // Server name (room/team)
	WAddress string `protobuf:"bytes,4,opt,name=WAddress,proto3" json:"WAddress,omitempty"`
	NewSync  bool   `protobuf:"varint,5,opt,name=NewSync,proto3" json:"NewSync,omitempty"`
}

func (x *ReqServerLogin) Reset() {
	*x = ReqServerLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqServerLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqServerLogin) ProtoMessage() {}

func (x *ReqServerLogin) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqServerLogin.ProtoReflect.Descriptor instead.
func (*ReqServerLogin) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *ReqServerLogin) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ReqServerLogin) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReqServerLogin) GetSerType() uint32 {
	if x != nil {
		return x.SerType
	}
	return 0
}

func (x *ReqServerLogin) GetWAddress() string {
	if x != nil {
		return x.WAddress
	}
	return ""
}

func (x *ReqServerLogin) GetNewSync() bool {
	if x != nil {
		return x.NewSync
	}
	return false
}

type RetServerLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *RetServerLogin) Reset() {
	*x = RetServerLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetServerLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetServerLogin) ProtoMessage() {}

func (x *RetServerLogin) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetServerLogin.ProtoReflect.Descriptor instead.
func (*RetServerLogin) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *RetServerLogin) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Sync room team
type ReqSyncRoomTeam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomState uint32 `protobuf:"varint,1,opt,name=RoomState,proto3" json:"RoomState,omitempty"`
	RServerId uint32 `protobuf:"varint,2,opt,name=RServerId,proto3" json:"RServerId,omitempty"` //RoomServer Id
	RAddress  string `protobuf:"bytes,3,opt,name=RAddress,proto3" json:"RAddress,omitempty"`    //RoomServer Address
	RoomId    uint32 `protobuf:"varint,4,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	MapId     uint32 `protobuf:"varint,12,opt,name=MapId,proto3" json:"MapId,omitempty"`
	NewSync   bool   `protobuf:"varint,13,opt,name=NewSync,proto3" json:"NewSync,omitempty"`
	EndTime   uint32 `protobuf:"varint,14,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
}

func (x *ReqSyncRoomTeam) Reset() {
	*x = ReqSyncRoomTeam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSyncRoomTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSyncRoomTeam) ProtoMessage() {}

func (x *ReqSyncRoomTeam) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSyncRoomTeam.ProtoReflect.Descriptor instead.
func (*ReqSyncRoomTeam) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *ReqSyncRoomTeam) GetRoomState() uint32 {
	if x != nil {
		return x.RoomState
	}
	return 0
}

func (x *ReqSyncRoomTeam) GetRServerId() uint32 {
	if x != nil {
		return x.RServerId
	}
	return 0
}

func (x *ReqSyncRoomTeam) GetRAddress() string {
	if x != nil {
		return x.RAddress
	}
	return ""
}

func (x *ReqSyncRoomTeam) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ReqSyncRoomTeam) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ReqSyncRoomTeam) GetNewSync() bool {
	if x != nil {
		return x.NewSync
	}
	return false
}

func (x *ReqSyncRoomTeam) GetEndTime() uint32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// Forward to other server's Client
type S2SClientCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint32 `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	UserId   uint64 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Data     []byte `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *S2SClientCmd) Reset() {
	*x = S2SClientCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SClientCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SClientCmd) ProtoMessage() {}

func (x *S2SClientCmd) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SClientCmd.ProtoReflect.Descriptor instead.
func (*S2SClientCmd) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *S2SClientCmd) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *S2SClientCmd) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *S2SClientCmd) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type S2SCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint32 `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	Flag     uint32 `protobuf:"varint,2,opt,name=Flag,proto3" json:"Flag,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *S2SCmd) Reset() {
	*x = S2SCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SCmd) ProtoMessage() {}

func (x *S2SCmd) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SCmd.ProtoReflect.Descriptor instead.
func (*S2SCmd) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

func (x *S2SCmd) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *S2SCmd) GetFlag() uint32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *S2SCmd) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

//Add Room
type ReqAddRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType uint32 `protobuf:"varint,1,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
	RoomId   uint32 `protobuf:"varint,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	EndTime  uint32 `protobuf:"varint,3,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
}

func (x *ReqAddRoom) Reset() {
	*x = ReqAddRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAddRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAddRoom) ProtoMessage() {}

func (x *ReqAddRoom) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAddRoom.ProtoReflect.Descriptor instead.
func (*ReqAddRoom) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *ReqAddRoom) GetRoomType() uint32 {
	if x != nil {
		return x.RoomType
	}
	return 0
}

func (x *ReqAddRoom) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ReqAddRoom) GetEndTime() uint32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type RetAddRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId uint32                  `protobuf:"varint,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	Datas  []*RetAddRoom_RTeamData `protobuf:"bytes,2,rep,name=Datas,proto3" json:"Datas,omitempty"`
}

func (x *RetAddRoom) Reset() {
	*x = RetAddRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetAddRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetAddRoom) ProtoMessage() {}

func (x *RetAddRoom) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetAddRoom.ProtoReflect.Descriptor instead.
func (*RetAddRoom) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

func (x *RetAddRoom) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RetAddRoom) GetDatas() []*RetAddRoom_RTeamData {
	if x != nil {
		return x.Datas
	}
	return nil
}

// Delete Room
type ReqRemoveRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   uint32 `protobuf:"varint,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	IsCustom bool   `protobuf:"varint,3,opt,name=IsCustom,proto3" json:"IsCustom,omitempty"`
}

func (x *ReqRemoveRoom) Reset() {
	*x = ReqRemoveRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqRemoveRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRemoveRoom) ProtoMessage() {}

func (x *ReqRemoveRoom) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRemoveRoom.ProtoReflect.Descriptor instead.
func (*ReqRemoveRoom) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{11}
}

func (x *ReqRemoveRoom) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ReqRemoveRoom) GetIsCustom() bool {
	if x != nil {
		return x.IsCustom
	}
	return false
}

//
type ReqEndGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId uint32 `protobuf:"varint,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *ReqEndGame) Reset() {
	*x = ReqEndGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqEndGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqEndGame) ProtoMessage() {}

func (x *ReqEndGame) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqEndGame.ProtoReflect.Descriptor instead.
func (*ReqEndGame) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{12}
}

func (x *ReqEndGame) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ReqEndGame) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ReqUpdateServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomNum uint32 `protobuf:"varint,1,opt,name=RoomNum,proto3" json:"RoomNum,omitempty"`
	UserNum uint32 `protobuf:"varint,2,opt,name=UserNum,proto3" json:"UserNum,omitempty"`
	RoomId  uint32 `protobuf:"varint,5,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
}

func (x *ReqUpdateServer) Reset() {
	*x = ReqUpdateServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUpdateServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdateServer) ProtoMessage() {}

func (x *ReqUpdateServer) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpdateServer.ProtoReflect.Descriptor instead.
func (*ReqUpdateServer) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{13}
}

func (x *ReqUpdateServer) GetRoomNum() uint32 {
	if x != nil {
		return x.RoomNum
	}
	return 0
}

func (x *ReqUpdateServer) GetUserNum() uint32 {
	if x != nil {
		return x.UserNum
	}
	return 0
}

func (x *ReqUpdateServer) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// Loading Config
type ReqLoadConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqLoadConfig) Reset() {
	*x = ReqLoadConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLoadConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLoadConfig) ProtoMessage() {}

func (x *ReqLoadConfig) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLoadConfig.ProtoReflect.Descriptor instead.
func (*ReqLoadConfig) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{14}
}

// Join room
type ReqTJointRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId  uint64 `protobuf:"varint,1,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	UserId   uint64 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName string `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName,omitempty"`
}

func (x *ReqTJointRoom) Reset() {
	*x = ReqTJointRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqTJointRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqTJointRoom) ProtoMessage() {}

func (x *ReqTJointRoom) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqTJointRoom.ProtoReflect.Descriptor instead.
func (*ReqTJointRoom) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{15}
}

func (x *ReqTJointRoom) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *ReqTJointRoom) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReqTJointRoom) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

//Room server Flag
type GameRoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	RoomId  uint32 `protobuf:"varint,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
}

func (x *GameRoomInfo) Reset() {
	*x = GameRoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameRoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRoomInfo) ProtoMessage() {}

func (x *GameRoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRoomInfo.ProtoReflect.Descriptor instead.
func (*GameRoomInfo) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{16}
}

func (x *GameRoomInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GameRoomInfo) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

//////////Game///////////
type ReqSyncFreePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomState uint32                     `protobuf:"varint,1,opt,name=RoomState,proto3" json:"RoomState,omitempty"`
	RServerId uint32                     `protobuf:"varint,2,opt,name=RServerId,proto3" json:"RServerId,omitempty"` // Room server id
	RAddress  string                     `protobuf:"bytes,3,opt,name=RAddress,proto3" json:"RAddress,omitempty"`
	Roomid    uint32                     `protobuf:"varint,4,opt,name=Roomid,proto3" json:"Roomid,omitempty"`
	Type      uint32                     `protobuf:"varint,5,opt,name=Type,proto3" json:"Type,omitempty"`
	RobotNum  uint32                     `protobuf:"varint,6,opt,name=RobotNum,proto3" json:"RobotNum,omitempty"`
	OwnerData *ReqSyncFreePlayer_MemData `protobuf:"bytes,7,opt,name=OwnerData,proto3" json:"OwnerData,omitempty"`
	NewSync   bool                       `protobuf:"varint,17,opt,name=NewSync,proto3" json:"NewSync,omitempty"`
}

func (x *ReqSyncFreePlayer) Reset() {
	*x = ReqSyncFreePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSyncFreePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSyncFreePlayer) ProtoMessage() {}

func (x *ReqSyncFreePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSyncFreePlayer.ProtoReflect.Descriptor instead.
func (*ReqSyncFreePlayer) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{17}
}

func (x *ReqSyncFreePlayer) GetRoomState() uint32 {
	if x != nil {
		return x.RoomState
	}
	return 0
}

func (x *ReqSyncFreePlayer) GetRServerId() uint32 {
	if x != nil {
		return x.RServerId
	}
	return 0
}

func (x *ReqSyncFreePlayer) GetRAddress() string {
	if x != nil {
		return x.RAddress
	}
	return ""
}

func (x *ReqSyncFreePlayer) GetRoomid() uint32 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *ReqSyncFreePlayer) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ReqSyncFreePlayer) GetRobotNum() uint32 {
	if x != nil {
		return x.RobotNum
	}
	return 0
}

func (x *ReqSyncFreePlayer) GetOwnerData() *ReqSyncFreePlayer_MemData {
	if x != nil {
		return x.OwnerData
	}
	return nil
}

func (x *ReqSyncFreePlayer) GetNewSync() bool {
	if x != nil {
		return x.NewSync
	}
	return false
}

type ReqReloadFreeMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId uint32 `protobuf:"varint,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *ReqReloadFreeMatch) Reset() {
	*x = ReqReloadFreeMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqReloadFreeMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqReloadFreeMatch) ProtoMessage() {}

func (x *ReqReloadFreeMatch) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqReloadFreeMatch.ProtoReflect.Descriptor instead.
func (*ReqReloadFreeMatch) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{18}
}

func (x *ReqReloadFreeMatch) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ReqReloadFreeMatch) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ReqSyncRoomTeam_MemData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ReqSyncRoomTeam_MemData) Reset() {
	*x = ReqSyncRoomTeam_MemData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSyncRoomTeam_MemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSyncRoomTeam_MemData) ProtoMessage() {}

func (x *ReqSyncRoomTeam_MemData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSyncRoomTeam_MemData.ProtoReflect.Descriptor instead.
func (*ReqSyncRoomTeam_MemData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ReqSyncRoomTeam_MemData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReqSyncRoomTeam_MemData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RetAddRoom_RTeamData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name uint32 `protobuf:"varint,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RetAddRoom_RTeamData) Reset() {
	*x = RetAddRoom_RTeamData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetAddRoom_RTeamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetAddRoom_RTeamData) ProtoMessage() {}

func (x *RetAddRoom_RTeamData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetAddRoom_RTeamData.ProtoReflect.Descriptor instead.
func (*RetAddRoom_RTeamData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10, 0}
}

func (x *RetAddRoom_RTeamData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RetAddRoom_RTeamData) GetName() uint32 {
	if x != nil {
		return x.Name
	}
	return 0
}

type ReqSyncFreePlayer_MemData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name string `protobuf:"bytes,10,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ReqSyncFreePlayer_MemData) Reset() {
	*x = ReqSyncFreePlayer_MemData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSyncFreePlayer_MemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSyncFreePlayer_MemData) ProtoMessage() {}

func (x *ReqSyncFreePlayer_MemData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSyncFreePlayer_MemData.ProtoReflect.Descriptor instead.
func (*ReqSyncFreePlayer_MemData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{17, 0}
}

func (x *ReqSyncFreePlayer_MemData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReqSyncFreePlayer_MemData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_server_proto protoreflect.FileDescriptor

var file_server_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x63, 0x6d, 0x64, 0x1a, 0x0d, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x67, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x22, 0x15, 0x0a,
	0x13, 0x52, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x42, 0x65, 0x61, 0x74, 0x22, 0x42, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x8c,
	0x01, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x53, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x53, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x57, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x57, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x53, 0x79, 0x6e, 0x63, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x4e, 0x65, 0x77, 0x53, 0x79, 0x6e, 0x63, 0x22, 0x20, 0x0a,
	0x0e, 0x52, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x22,
	0xfa, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x6f, 0x6f, 0x6d, 0x54,
	0x65, 0x61, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x52, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x52, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x52, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x4d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x77,
	0x53, 0x79, 0x6e, 0x63, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x4e, 0x65, 0x77, 0x53,
	0x79, 0x6e, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x2d, 0x0a,
	0x07, 0x4d, 0x65, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x56, 0x0a, 0x0c,
	0x53, 0x32, 0x53, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x4c, 0x0a, 0x06, 0x53, 0x32, 0x53, 0x43, 0x6d, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x6c,
	0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x5a, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d,
	0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x8a,
	0x01, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x05, 0x44, 0x61, 0x74, 0x61, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6d, 0x64, 0x2e, 0x52,
	0x65, 0x74, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x54, 0x65, 0x61, 0x6d, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x05, 0x44, 0x61, 0x74, 0x61, 0x73, 0x1a, 0x2f, 0x0a, 0x09, 0x52, 0x54,
	0x65, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x43, 0x0a, 0x0d, 0x52,
	0x65, 0x71, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x49, 0x73, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x22, 0x3c, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5d,
	0x0a, 0x0f, 0x52, 0x65, 0x71, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x55,
	0x73, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x55, 0x73,
	0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x0f, 0x0a,
	0x0d, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x5d,
	0x0a, 0x0d, 0x52, 0x65, 0x71, 0x54, 0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12,
	0x18, 0x0a, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a,
	0x0c, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22,
	0xbe, 0x02, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x53, 0x79, 0x6e, 0x63, 0x46, 0x72, 0x65, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x52, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52,
	0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x62,
	0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x52, 0x6f, 0x62,
	0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x40, 0x0a, 0x09, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63,
	0x6d, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x79, 0x6e, 0x63, 0x46, 0x72, 0x65, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x53, 0x79,
	0x6e, 0x63, 0x18, 0x11, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x4e, 0x65, 0x77, 0x53, 0x79, 0x6e,
	0x63, 0x1a, 0x2d, 0x0a, 0x07, 0x4d, 0x65, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x44, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x72, 0x65,
	0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x2a, 0xdd, 0x02, 0x0a, 0x07, 0x43, 0x6d, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x32, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x53, 0x65, 0x72,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x68, 0x6b,
	0x52, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x79, 0x6e,
	0x63, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x65, 0x61, 0x6d, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x53,
	0x32, 0x53, 0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x10, 0x08, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x10,
	0x11, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x10,
	0x12, 0x12, 0x0e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x10,
	0x13, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x14, 0x12, 0x10,
	0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x15,
	0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x69, 0x6e, 0x66, 0x69, 0x67, 0x10, 0x16,
	0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x20,
	0x12, 0x0d, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x10, 0x25, 0x12,
	0x15, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x53, 0x65, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x10, 0xad, 0x02, 0x12, 0x17, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0xb0, 0x02, 0x12,
	0x18, 0x0a, 0x13, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0xb1, 0x02, 0x12, 0x14, 0x0a, 0x0f, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x10, 0x91, 0x4e, 0x12,
	0x15, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42,
	0x65, 0x61, 0x74, 0x10, 0x92, 0x4e, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x75, 0x73, 0x65,
	0x72, 0x63, 0x6d, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData = file_server_proto_rawDesc
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_proto_rawDescData)
	})
	return file_server_proto_rawDescData
}

var file_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_server_proto_goTypes = []interface{}{
	(CmdType)(0),                      // 0: usercmd.CmdType
	(*ReqServiceHeartBeat)(nil),       // 1: usercmd.ReqServiceHeartBeat
	(*RetServiceHeartBeat)(nil),       // 2: usercmd.RetServiceHeartBeat
	(*ReqRegisterService)(nil),        // 3: usercmd.ReqRegisterService
	(*RetRegisterService)(nil),        // 4: usercmd.RetRegisterService
	(*ReqServerLogin)(nil),            // 5: usercmd.ReqServerLogin
	(*RetServerLogin)(nil),            // 6: usercmd.RetServerLogin
	(*ReqSyncRoomTeam)(nil),           // 7: usercmd.ReqSyncRoomTeam
	(*S2SClientCmd)(nil),              // 8: usercmd.S2SClientCmd
	(*S2SCmd)(nil),                    // 9: usercmd.S2SCmd
	(*ReqAddRoom)(nil),                // 10: usercmd.ReqAddRoom
	(*RetAddRoom)(nil),                // 11: usercmd.RetAddRoom
	(*ReqRemoveRoom)(nil),             // 12: usercmd.ReqRemoveRoom
	(*ReqEndGame)(nil),                // 13: usercmd.ReqEndGame
	(*ReqUpdateServer)(nil),           // 14: usercmd.ReqUpdateServer
	(*ReqLoadConfig)(nil),             // 15: usercmd.ReqLoadConfig
	(*ReqTJointRoom)(nil),             // 16: usercmd.ReqTJointRoom
	(*GameRoomInfo)(nil),              // 17: usercmd.GameRoomInfo
	(*ReqSyncFreePlayer)(nil),         // 18: usercmd.ReqSyncFreePlayer
	(*ReqReloadFreeMatch)(nil),        // 19: usercmd.ReqReloadFreeMatch
	(*ReqSyncRoomTeam_MemData)(nil),   // 20: usercmd.ReqSyncRoomTeam.MemData
	(*RetAddRoom_RTeamData)(nil),      // 21: usercmd.RetAddRoom.RTeamData
	(*ReqSyncFreePlayer_MemData)(nil), // 22: usercmd.ReqSyncFreePlayer.MemData
}
var file_server_proto_depIdxs = []int32{
	21, // 0: usercmd.RetAddRoom.Datas:type_name -> usercmd.RetAddRoom.RTeamData
	22, // 1: usercmd.ReqSyncFreePlayer.OwnerData:type_name -> usercmd.ReqSyncFreePlayer.MemData
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	file_base_go_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqServiceHeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetServiceHeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqRegisterService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetRegisterService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqServerLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetServerLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSyncRoomTeam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SClientCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAddRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetAddRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqRemoveRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqEndGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUpdateServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLoadConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqTJointRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameRoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSyncFreePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqReloadFreeMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSyncRoomTeam_MemData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetAddRoom_RTeamData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSyncFreePlayer_MemData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		EnumInfos:         file_server_proto_enumTypes,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_rawDesc = nil
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
